import { SUPABASE_URL, SUPABASE_ANON_KEY } from './config.js';

const STORAGE_KEY = 'inmigracion-alemania-2028.tasks.v1';
const THEME_KEY = 'inmigracion-alemania-2028.theme';
const GOAL_DATE = '2028-06-30';
const STATUSES = ['Sin empezar', 'En progreso', 'Listo'];
const AREAS = ['Idiomas','Migratorio','Recursos','Postulación','Salud','Marca/Ingresos','Logística ciudad'];
const COLORS = {Idiomas:'#4fb3a5',Migratorio:'#e0705a',Recursos:'#7ec97f',Postulación:'#a98af0',Salud:'#e08ac0','Marca/Ingresos':'#e8a33d','Logística ciudad':'#8aa6f0'};
const TRACKER_KEY = 'inmigracion-alemania-2028.trackers.v1';
const TRACKER_DEFAULTS = [
  {slug:'savings',title:'Ahorro para Alemania',kind:'savings',current_value:0,target_value:40500000,progress:0,notes:'Meta: colchón, tiquetes y trámites.',color:'#56c0b0'},
  {slug:'debt',title:'Pago de deuda',kind:'debt',current_value:0,target_value:13000000,progress:0,notes:'Registra el total abonado a la deuda actual.',color:'#eb806b'},
  {slug:'ecommerce',title:'E-commerce',kind:'ecommerce',current_value:0,target_value:100,progress:0,notes:'Define nicho, proveedor y primeras ventas.',color:'#a98af0'}
];
const seed = [
['TOEFL — meta 80+','Idiomas','En progreso','2026-08-31',''],['Alemán A1','Idiomas','Sin empezar','2027-01-31',''],['Alemán A2','Idiomas','Sin empezar','2027-07-31',''],['Alemán B1','Idiomas','Sin empezar','2028-01-31',''],['Certificación oficial alemán (Goethe/telc)','Idiomas','Sin empezar','2028-01-31',''],['Definir fecha de matrimonio con Johan','Migratorio','Sin empezar','2027-06-30',''],['Trámite notarial de matrimonio','Migratorio','Sin empezar','2027-06-30',''],['Visa de cónyuge (Johan)','Migratorio','Sin empezar','','Depende de matrimonio + admisión/beca confirmada'],['Visa de estudiante (ambos)','Migratorio','Sin empezar','2028-03-31','Iniciar 3-6 meses antes del viaje'],['Pagar deuda actual (13M)','Recursos','Sin empezar','2027-07-31',''],['Ahorro colchón + tiquetes + notarial (~40.5M)','Recursos','Sin empezar','2028-06-30','~2.23M/mes entre los dos'],['Gestión del préstamo (25M restante del colchón)','Recursos','Sin empezar','2027-12-31',''],['Verificar requisitos cuenta bloqueada alemana','Recursos','Sin empezar','2027-09-30',''],['Confirmar programa STEM/EPOS por universidad','Postulación','Sin empezar','2026-12-31',''],['Aplicación DAAD/EPOS','Postulación','Sin empezar','2027-11-30',''],['Aplicación Rosa-Luxemburg-Stiftung','Postulación','Sin empezar','2027-11-30',''],['Plan B: Erasmus Mundus (consorcio 1 país)','Postulación','Sin empezar','2028-02-28',''],['Plan B: Stipendium Hungaricum','Postulación','Sin empezar','2028-01-31',''],['Confirmación de admisión','Postulación','Sin empezar','2028-06-30',''],['Chequeos médicos completos (ambos)','Salud','Sin empezar','2027-06-30',''],['LinkedIn — comunicadora médica/regulatory','Marca/Ingresos','Sin empezar','2026-08-31',''],['Instagram con amiga — flashcards/journey','Marca/Ingresos','Sin empezar','2026-08-31',''],['E-commerce — definir nicho y proveedor','Marca/Ingresos','Sin empezar','2026-12-31',''],['Plantillas/automatización para vender','Marca/Ingresos','Sin empezar','2027-03-31',''],['Plan de negocio laboratorio biomédico','Marca/Ingresos','Sin empezar','','Sin fecha crítica, ingreso pasivo'],['Evaluar ciudades finales (costo, empleo, arriendo, seguridad)','Logística ciudad','Sin empezar','2027-03-31',''],['Posible viaje a conferencia en Alemania (si sigue en Systemed)','Logística ciudad','Sin empezar','2026-11-30','Aún no confirmado']
].map(([tarea,area,estado,fecha,notas],i)=>({id:`seed-${i}`,tarea,area,estado,fecha,notas}));

let tasks = readLocal(); let trackers = readTrackers(); let editingId = null; let editingTracker = null; let loginMode = 'signin'; let supabase = null; let user = null;
const $ = id => document.getElementById(id);
function safeTask(raw) { return { id: String(raw.id || crypto.randomUUID()), tarea: String(raw.tarea || '').trim().slice(0,160), area: AREAS.includes(raw.area) ? raw.area : 'Idiomas', estado: STATUSES.includes(raw.estado) ? raw.estado : 'Sin empezar', fecha: /^\d{4}-\d{2}-\d{2}$/.test(raw.fecha || '') ? raw.fecha : '', notas: String(raw.notas || '').trim().slice(0,1000) }; }
function readLocal() { try { const data = JSON.parse(localStorage.getItem(STORAGE_KEY)); return Array.isArray(data) ? data.map(safeTask).filter(t=>t.tarea) : structuredClone(seed); } catch { return structuredClone(seed); } }
function saveLocal() { localStorage.setItem(STORAGE_KEY, JSON.stringify(tasks)); }
function readTrackers() { try { const data=JSON.parse(localStorage.getItem(TRACKER_KEY)); if(Array.isArray(data)&&data.length===3)return data; } catch {} return structuredClone(TRACKER_DEFAULTS); }
function saveTrackers() { localStorage.setItem(TRACKER_KEY,JSON.stringify(trackers)); }
function daysUntil(date) { if (!date) return null; const [y,m,d] = date.split('-').map(Number); const target = Date.UTC(y,m-1,d); const now = new Date(); const today = Date.UTC(now.getFullYear(),now.getMonth(),now.getDate()); return Math.round((target-today)/86400000); }
function formatDate(date) { if (!date) return ''; const [y,m,d] = date.split('-').map(Number); return new Intl.DateTimeFormat('es-CO',{day:'2-digit',month:'short',year:'numeric',timeZone:'UTC'}).format(new Date(Date.UTC(y,m-1,d))); }
function el(tag, cls, text) { const node=document.createElement(tag); if(cls)node.className=cls; if(text !== undefined)node.textContent=text; return node; }
function toast(message) { const t=$('toast'); t.textContent=message; t.classList.add('show'); clearTimeout(toast.timer); toast.timer=setTimeout(()=>t.classList.remove('show'),3000); }
function setTheme(theme) { document.documentElement.dataset.theme=theme; localStorage.setItem(THEME_KEY,theme); const light=theme==='light'; $('themeBtn').querySelector('[aria-hidden=true]').textContent=light?'☾':'☀'; $('themeLabel').textContent=light?'Oscuro':'Claro'; $('themeBtn').setAttribute('aria-label',`Cambiar a modo ${light?'oscuro':'claro'}`); }
function setLoginMode(mode) { loginMode=mode; const signup=mode==='signup', setPassword=mode==='setpassword'; $('loginTitle').textContent=setPassword?'Crear contraseña':signup?'Crear cuenta':'Iniciar sesión'; $('loginHelp').textContent=setPassword?'Elige una contraseña de al menos 8 caracteres para no volver a necesitar enlaces por correo.':signup?'Crea una contraseña de al menos 8 caracteres. Solo tendrás que confirmar tu correo una vez.':'Usa tu correo y contraseña para sincronizar tus datos.'; $('loginEmailLabel').hidden=setPassword; $('loginEmail').required=!setPassword; $('loginPassword').autocomplete=(signup||setPassword)?'new-password':'current-password'; $('loginSubmit').textContent=setPassword?'Guardar contraseña':signup?'Crear cuenta':'Ingresar'; $('toggleSignup').hidden=setPassword; $('toggleSignup').textContent=signup?'Ya tengo cuenta':'Crear cuenta'; }
function filtered() { const q=$('search').value.trim().toLocaleLowerCase('es'); const area=$('areaFilter').value, status=$('statusFilter').value; return tasks.filter(t => (!q || `${t.tarea} ${t.notas}`.toLocaleLowerCase('es').includes(q)) && (area==='Todas'||t.area===area) && (status==='Todos'||t.estado===status)); }
function renderStats() { const done=tasks.filter(t=>t.estado==='Listo').length, pct=tasks.length?Math.round(done/tasks.length*100):0; $('globalProgress').textContent=`${pct}%`; $('globalBar').style.width=`${pct}%`; $('taskCount').textContent=tasks.length; $('doneCount').textContent=`${done} completadas`; const root=$('areaProgress'); root.replaceChildren(); AREAS.forEach(area=>{const a=tasks.filter(t=>t.area===area), d=a.filter(t=>t.estado==='Listo').length; if(a.length) root.append(el('span','area-pill',`${area}: ${Math.round(d/a.length*100)}%`));}); }
function money(value) { return new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(Number(value)||0); }
function trackerPct(tracker) { return tracker.kind==='ecommerce' ? Math.max(0,Math.min(100,Number(tracker.progress)||0)) : Math.max(0,Math.min(100,Math.round((Number(tracker.current_value)||0)/(Number(tracker.target_value)||1)*100))); }
function renderTrackers() { const root=$('trackers'); root.replaceChildren(); trackers.forEach(t=>{const card=el('article','tracker');card.style.setProperty('--tracker-color',t.color);const head=el('div','tracker-head'),titleBox=el('div');titleBox.append(el('p','tracker-kicker',t.kind==='savings'?'Meta financiera':t.kind==='debt'?'Compromiso financiero':'Proyecto de ingresos'),el('h3','tracker-name',t.title));const edit=el('button','tracker-edit','Actualizar');edit.type='button';edit.onclick=()=>openTracker(t.slug);head.append(titleBox,edit);const pct=trackerPct(t),value=el('p','tracker-value');if(t.kind==='ecommerce'){value.textContent=`${pct}%`;value.append(el('small','', ' de avance'));}else{value.textContent=money(t.current_value);value.append(el('small','',` de ${money(t.target_value)}`));}const progress=el('div','progress');const bar=el('i');bar.style.width=`${pct}%`;bar.style.background=`linear-gradient(90deg,${t.color},${t.color}aa)`;progress.append(bar);const footer=el('div','tracker-footer');footer.append(el('span','',`${pct}% completado`),el('span','',t.kind==='debt'?`Faltan ${money(Math.max(0,t.target_value-t.current_value))}`:t.kind==='savings'?`Faltan ${money(Math.max(0,t.target_value-t.current_value))}`:'Plan de negocio'));card.append(head,value,progress,footer,el('p','tracker-note',t.notes||'Sin notas todavía.'));root.append(card);}); }
function makeCard(task) { const card=el('article','card'); card.draggable=true; card.dataset.id=task.id; card.style.setProperty('--area',COLORS[task.area]); card.append(el('p','card-title',task.tarea)); const meta=el('div','meta'); meta.append(el('span','',task.area)); if(task.fecha){const d=daysUntil(task.fecha), due=el('span',`due ${d<0?'overdue':d<=30?'soon':'ok'}`,formatDate(task.fecha)); due.title=d<0?`${Math.abs(d)} días vencida`:d===0?'Vence hoy':`Faltan ${d} días`;meta.append(due);} card.append(meta); if(task.notas)card.append(el('p','notes',task.notas)); card.addEventListener('click',()=>openTask(task.id)); card.addEventListener('dragstart',e=>{card.classList.add('dragging');e.dataTransfer.setData('text/plain',task.id);e.dataTransfer.effectAllowed='move';}); card.addEventListener('dragend',()=>card.classList.remove('dragging')); return card; }
function renderBoard() { const board=$('board'); board.replaceChildren(); const visible=filtered(); STATUSES.forEach(status=>{const col=el('section','col'); col.dataset.status=status; const head=el('div','col-head'); head.append(el('span','',status),el('b','',String(visible.filter(t=>t.estado===status).length))); col.append(head); const list=visible.filter(t=>t.estado===status).sort((a,b)=>(a.fecha||'9999').localeCompare(b.fecha||'9999')); list.length ? list.forEach(t=>col.append(makeCard(t))) : col.append(el('p','empty','Sin tareas')); col.addEventListener('dragover',e=>{e.preventDefault();col.classList.add('drag-over');}); col.addEventListener('dragleave',()=>col.classList.remove('drag-over')); col.addEventListener('drop',async e=>{e.preventDefault();col.classList.remove('drag-over');const id=e.dataTransfer.getData('text/plain'), task=tasks.find(t=>t.id===id);if(task&&task.estado!==status){task.estado=status;await persist(task);render();}});board.append(col);}); }
function render(){ $('countdownN').textContent=daysUntil(GOAL_DATE).toLocaleString('es-CO'); renderStats(); renderTrackers(); renderBoard(); }
function openTask(id) { editingId=id; const t=id?tasks.find(x=>x.id===id):{tarea:'',area:'Idiomas',estado:'Sin empezar',fecha:'',notas:''}; $('dialogTitle').textContent=id?'Editar tarea':'Nueva tarea'; ['Tarea','Area','Estado','Fecha','Notas'].forEach(k=>$(`f${k}`).value=t[k.toLowerCase()]||''); $('deleteBtn').hidden=!id; $('taskDialog').showModal(); }
async function persist(task) { saveLocal(); if(user&&supabase){const row={id:task.id,user_id:user.id,tarea:task.tarea,area:task.area,estado:task.estado,fecha:task.fecha||null,notas:task.notas};const {error}=await supabase.from('tasks').upsert(row);if(error)toast(`No se pudo sincronizar: ${error.message}`);} }
async function loadTrackers() { if(!user||!supabase)return; const {data,error}=await supabase.from('trackers').select('*').order('slug');if(error){toast(`No se pudieron cargar los trackers: ${error.message}`);return;} if(data.length){trackers=data.map(row=>({...TRACKER_DEFAULTS.find(t=>t.slug===row.slug),...row}));saveTrackers();}else{for(const tracker of trackers)await persistTracker(tracker);} }
async function persistTracker(tracker) { saveTrackers(); if(user&&supabase){const row={user_id:user.id,slug:tracker.slug,title:tracker.title,kind:tracker.kind,current_value:Number(tracker.current_value)||0,target_value:Number(tracker.target_value)||0,progress:Number(tracker.progress)||0,notes:String(tracker.notes||'').slice(0,500)};const {data,error}=await supabase.from('trackers').upsert(row,{onConflict:'user_id,slug'}).select().single();if(error)toast(`No se pudo guardar el tracker: ${error.message}`);else if(data){Object.assign(tracker,data);saveTrackers();}} }
function openTracker(slug) { editingTracker=slug;const t=trackers.find(x=>x.slug===slug), ecom=t.kind==='ecommerce';$('trackerDialogTitle').textContent=`Actualizar: ${t.title}`;$('trackerDialogHelp').textContent=ecom?'Registra el avance general de tu proyecto de e-commerce.':'Actualiza el monto acumulado; los valores se guardan en pesos colombianos.';$('trackerCurrentLabel').hidden=ecom;$('trackerTargetLabel').hidden=ecom;$('trackerProgressLabel').hidden=!ecom;$('trackerCurrent').required=!ecom;$('trackerTarget').required=!ecom;$('trackerCurrent').value=t.current_value;$('trackerTarget').value=t.target_value;$('trackerProgress').value=trackerPct(t);$('trackerNotes').value=t.notes||'';$('trackerDialog').showModal(); }
async function removeTask(id) { tasks=tasks.filter(t=>t.id!==id);saveLocal();if(user&&supabase){const {error}=await supabase.from('tasks').delete().eq('id',id);if(error)toast(`No se pudo borrar en nube: ${error.message}`);} }
async function replaceRemote() { if(!user||!supabase)return; const {error:removeError}=await supabase.from('tasks').delete().eq('user_id',user.id); if(removeError){toast(`No se pudo actualizar la nube: ${removeError.message}`);return;} for(const task of tasks) await persist(task); }
async function setupSupabase() { if(!SUPABASE_URL||!SUPABASE_ANON_KEY)return; try { const {createClient}=await import('https://esm.sh/@supabase/supabase-js@2'); supabase=createClient(SUPABASE_URL,SUPABASE_ANON_KEY); $('syncPanel').hidden=false; const {data:{session}}=await supabase.auth.getSession(); if(session) await signedIn(session.user); } catch { toast('No se pudo iniciar Supabase. Se mantiene el modo local.'); } }
async function signedIn(nextUser) { user=nextUser; $('syncStatus').textContent=`Sincronizado: ${user.email}`;$('loginBtn').hidden=true;$('setPasswordBtn').hidden=false;$('logoutBtn').hidden=false; const {data,error}=await supabase.from('tasks').select('*').order('created_at');if(error){toast(`Error de nube: ${error.message}`);return;} if(data.length){tasks=data.map(safeTask);saveLocal();} else { /* Las tareas semilla no pueden compartir IDs entre cuentas distintas. */ tasks=tasks.map(task=>({...task,id:crypto.randomUUID()}));saveLocal();for(const task of tasks) await persist(task);} await loadTrackers(); supabase.channel(`tasks-${user.id}`).on('postgres_changes',{event:'*',schema:'public',table:'tasks',filter:`user_id=eq.${user.id}`},async()=>{const {data}=await supabase.from('tasks').select('*').order('created_at');if(data){tasks=data.map(safeTask);saveLocal();render();}}).subscribe(); supabase.channel(`trackers-${user.id}`).on('postgres_changes',{event:'*',schema:'public',table:'trackers',filter:`user_id=eq.${user.id}`},async()=>{await loadTrackers();render();}).subscribe();render(); }

AREAS.forEach(a=>$('areaFilter').append(new Option(a,a))); AREAS.forEach(a=>$('fArea').append(new Option(a,a)));
$('search').addEventListener('input',renderBoard); $('areaFilter').addEventListener('change',renderBoard); $('statusFilter').addEventListener('change',renderBoard); $('addBtn').onclick=()=>openTask(null);
$('themeBtn').onclick=()=>setTheme(document.documentElement.dataset.theme==='light'?'dark':'light');
$('closeTracker').onclick=()=>$('trackerDialog').close(); $('cancelTracker').onclick=()=>$('trackerDialog').close(); $('trackerForm').onsubmit=async e=>{e.preventDefault();const t=trackers.find(x=>x.slug===editingTracker);if(!t)return; if(t.kind==='ecommerce'){t.progress=Math.max(0,Math.min(100,Number($('trackerProgress').value)||0));}else{t.current_value=Math.max(0,Number($('trackerCurrent').value)||0);t.target_value=Math.max(0,Number($('trackerTarget').value)||0);}t.notes=$('trackerNotes').value.trim().slice(0,500);await persistTracker(t);$('trackerDialog').close();render();toast('Tracker actualizado.');};
$('taskForm').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget;if(!form.reportValidity())return;const raw={tarea:$('fTarea').value,area:$('fArea').value,estado:$('fEstado').value,fecha:$('fFecha').value,notas:$('fNotas').value};const task=safeTask({...raw,id:editingId||crypto.randomUUID()});if(editingId){tasks[tasks.findIndex(t=>t.id===editingId)]=task;}else tasks.push(task);await persist(task);$('taskDialog').close();render();});
$('deleteBtn').onclick=async()=>{if(editingId&&confirm('¿Eliminar esta tarea?')){await removeTask(editingId);$('taskDialog').close();render();}};
$('exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),tasks},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='inmigracion-alemania-2028.json';a.click();URL.revokeObjectURL(a.href);};
$('importInput').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const parsed=JSON.parse(await file.text());const incoming=Array.isArray(parsed)?parsed:parsed.tasks;if(!Array.isArray(incoming))throw new Error();const clean=incoming.map(safeTask).filter(t=>t.tarea);if(!clean.length)throw new Error();if(!confirm(`Se reemplazarán las ${tasks.length} tareas actuales por ${clean.length}. ¿Continuar?`))return;tasks=clean;saveLocal();await replaceRemote();render();toast('Datos importados.');}catch{toast('Archivo JSON inválido. No se importó nada.');}finally{e.target.value='';}};
$('loginBtn').onclick=()=>{setLoginMode('signin');$('loginDialog').showModal();}; $('setPasswordBtn').onclick=()=>{setLoginMode('setpassword');$('loginDialog').showModal();}; $('closeLogin').onclick=()=>$('loginDialog').close(); $('toggleSignup').onclick=()=>setLoginMode(loginMode==='signin'?'signup':'signin'); $('loginForm').onsubmit=async e=>{e.preventDefault();const email=$('loginEmail').value.trim(),password=$('loginPassword').value;if(loginMode==='setpassword'){const {error}=await supabase.auth.updateUser({password});if(error)toast(error.message);else{$('loginDialog').close();toast('Contraseña creada. Desde ahora puedes iniciar sesión normalmente.');}}else if(loginMode==='signup'){const {data,error}=await supabase.auth.signUp({email,password,options:{emailRedirectTo:location.href}});if(error)toast(error.message);else if(data.session){$('loginDialog').close();await signedIn(data.user);toast('Cuenta creada y sesión iniciada.');}else{toast('Revisa tu correo una vez para confirmar tu cuenta.');$('loginDialog').close();}}else{const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error)toast('Correo o contraseña incorrectos.');else{$('loginDialog').close();await signedIn(data.user);}}}; $('logoutBtn').onclick=async()=>{await supabase.auth.signOut();user=null;$('syncStatus').textContent='Modo local';$('loginBtn').hidden=false;$('setPasswordBtn').hidden=true;$('logoutBtn').hidden=true;};
setTheme(localStorage.getItem(THEME_KEY)==='light'?'light':'dark'); render(); setupSupabase();

